version: '2'
services:
  todo-mysql:
    build: "./todo-mysql"
    container_name: "todo-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: todo
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: todo
    ports:
     - "3306:3306"
  todo-backend:
    build: "./todo-backend"
    container_name: "todo-backend"
    ports:
     - "8080:8080"
    depends_on: 
     - todo-mysql
    entrypoint: ./wait-for-it.sh todo-mysql:3306 -- java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar /app.jar
  todo-frontend:
    build: "./todo-frontend"
    container_name: "todo-frontend"
    ports:
     - "80:80"
    volumes:
     - ./todo-frontend/dist:/usr/share/nginx/html/
    depends_on: 
     - todo-backend